set -g mouse on

setw -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "pbcopy"

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"

# iTerm2 tmux integration best practices
set -g default-terminal "xterm-256color"
set-option -g allow-passthrough on
set-option -g set-titles on
set-option -g set-titles-string "#T"
